'use client';

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { 
  CheckCircle2, 
  XCircle, 
  ArrowRight, 
  Loader2, 
  Trophy,
  BrainCircuit,
  MessageCircle
} from 'lucide-react';
import { generatePersonalizedQuiz, type GeneratePersonalizedQuizOutput } from '@/ai/flows/ai-personalized-quiz';

type QuizState = 'idle' | 'loading' | 'active' | 'results';

export default function QuizComponent({ topic }: { topic: string }) {
  const [state, setState] = useState<QuizState>('idle');
  const [quiz, setQuiz] = useState<GeneratePersonalizedQuizOutput | null>(null);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedOption, setSelectedOption] = useState<string | null>(null);
  const [score, setScore] = useState(0);
  const [showExplanation, setShowExplanation] = useState(false);

  const startQuiz = async () => {
    setState('loading');
    try {
      const data = await generatePersonalizedQuiz({
        topic,
        difficulty: 'beginner',
        userPerformanceData: "New user starting their journey. Focus on core concepts like qubits and superposition."
      });
      setQuiz(data);
      setState('active');
    } catch (error) {
      console.error(error);
      setState('idle');
    }
  };

  const handleOptionSelect = (option: string) => {
    if (showExplanation) return;
    setSelectedOption(option);
  };

  const submitAnswer = () => {
    if (!selectedOption) return;
    const isCorrect = selectedOption === quiz?.questions[currentIdx].correctAnswer;
    if (isCorrect) setScore(s => s + 1);
    setShowExplanation(true);
  };

  const nextQuestion = () => {
    if (currentIdx + 1 < (quiz?.questions.length || 0)) {
      setCurrentIdx(i => i + 1);
      setSelectedOption(null);
      setShowExplanation(false);
    } else {
      setState('results');
    }
  };

  if (state === 'idle') {
    return (
      <Card className="glass-card p-12 flex flex-col items-center text-center gap-6">
        <div className="w-16 h-16 bg-primary/20 rounded-full flex items-center justify-center text-primary">
          <BrainCircuit className="w-10 h-10" />
        </div>
        <div>
          <h3 className="text-2xl font-headline font-bold text-white mb-2">Test Your Knowledge</h3>
          <p className="text-muted-foreground max-w-md">Take a personalized quiz on {topic} generated by Professor Quantum just for you.</p>
        </div>
        <Button onClick={startQuiz} className="bg-primary hover:bg-primary/90 neon-violet font-bold px-10 h-12 rounded-full">
          Start Quiz Session
        </Button>
      </Card>
    );
  }

  if (state === 'loading') {
    return (
      <Card className="glass-card p-12 flex flex-col items-center justify-center min-h-[400px] gap-6">
        <Loader2 className="w-12 h-12 text-primary animate-spin" />
        <div className="text-center">
          <p className="text-lg font-bold text-white animate-pulse">Generating personalized questions...</p>
          <p className="text-sm text-muted-foreground mt-2">Professor Quantum is analyzing your learning path.</p>
        </div>
      </Card>
    );
  }

  if (state === 'active' && quiz) {
    const question = quiz.questions[currentIdx];
    const progress = ((currentIdx + 1) / quiz.questions.length) * 100;

    return (
      <Card className="glass-card p-8 flex flex-col gap-8 min-h-[500px]">
        <div className="flex items-center justify-between">
          <Badge variant="outline" className="border-primary/30 text-primary uppercase tracking-widest text-[10px]">
            Question {currentIdx + 1} of {quiz.questions.length}
          </Badge>
          <div className="flex items-center gap-4">
            <span className="text-[10px] uppercase tracking-widest text-muted-foreground">{Math.round(progress)}% Complete</span>
            <Progress value={progress} className="w-24 h-1.5" />
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-xl font-headline font-bold text-white leading-tight">
            {question.questionText}
          </h3>
          <div className="grid grid-cols-1 gap-3">
            {question.options.map((option, i) => {
              const isSelected = selectedOption === option;
              const isCorrect = option === question.correctAnswer;
              const isWrong = isSelected && !isCorrect;

              let styles = "justify-start h-14 text-left px-6 border-white/5 bg-white/5 hover:bg-white/10 rounded-xl";
              if (isSelected) styles = "justify-start h-14 text-left px-6 border-primary/50 bg-primary/10 text-white rounded-xl";
              if (showExplanation && isCorrect) styles = "justify-start h-14 text-left px-6 border-green-500/50 bg-green-500/20 text-green-400 rounded-xl";
              if (showExplanation && isWrong) styles = "justify-start h-14 text-left px-6 border-red-500/50 bg-red-500/20 text-red-400 rounded-xl";

              return (
                <Button
                  key={i}
                  variant="outline"
                  onClick={() => handleOptionSelect(option)}
                  className={styles}
                  disabled={showExplanation}
                >
                  <span className="w-6 h-6 rounded-full border border-white/20 flex items-center justify-center mr-4 text-[10px] font-bold shrink-0">
                    {String.fromCharCode(65 + i)}
                  </span>
                  <span className="flex-1">{option}</span>
                  {showExplanation && isCorrect && <CheckCircle2 className="w-5 h-5 ml-2" />}
                  {showExplanation && isWrong && <XCircle className="w-5 h-5 ml-2" />}
                </Button>
              );
            })}
          </div>
        </div>

        {showExplanation ? (
          <div className="bg-primary/5 border border-white/5 rounded-xl p-6 space-y-3 animate-in fade-in slide-in-from-bottom-2 duration-500">
            <div className="flex items-center gap-2 text-primary">
              <MessageCircle className="w-4 h-4" />
              <span className="text-xs font-bold uppercase tracking-widest">Professor's Insight</span>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {question.explanation}
            </p>
            <Button onClick={nextQuestion} className="w-full bg-primary hover:bg-primary/90 mt-4 h-12 font-bold group rounded-full">
              {currentIdx + 1 === quiz.questions.length ? 'View Final Score' : 'Next Question'}
              <ArrowRight className="ml-2 w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </Button>
          </div>
        ) : (
          <Button 
            disabled={!selectedOption} 
            onClick={submitAnswer} 
            className="w-full h-12 bg-primary hover:bg-primary/90 neon-violet font-bold mt-auto rounded-full"
          >
            Check Answer
          </Button>
        )}
      </Card>
    );
  }

  if (state === 'results' && quiz) {
    const percentage = (score / quiz.questions.length) * 100;
    return (
      <Card className="glass-card p-12 flex flex-col items-center text-center gap-8">
        <div className="relative">
          <div className="w-24 h-24 bg-primary/20 rounded-full flex items-center justify-center text-primary">
            <Trophy className="w-12 h-12" />
          </div>
          <div className="absolute inset-0 bg-primary/20 blur-2xl rounded-full" />
        </div>
        
        <div className="space-y-2">
          <h3 className="text-3xl font-headline font-bold text-white">Quiz Completed!</h3>
          <p className="text-muted-foreground">You've mastered the basics of {topic}.</p>
        </div>

        <div className="flex gap-12">
          <div className="text-center">
            <div className="text-4xl font-headline font-bold text-white">{score}</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-widest mt-1">Score</div>
          </div>
          <div className="text-center">
            <div className="text-4xl font-headline font-bold text-primary">{Math.round(percentage)}%</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-widest mt-1">Accuracy</div>
          </div>
          <div className="text-center">
            <div className="text-4xl font-headline font-bold text-accent">+150</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-widest mt-1">XP Gained</div>
          </div>
        </div>

        <div className="w-full flex gap-4">
          <Button onClick={startQuiz} variant="outline" className="flex-1 border-white/10 hover:bg-white/5 h-12 font-bold rounded-full">
            Retake Quiz
          </Button>
          <Button className="flex-1 bg-primary hover:bg-primary/90 h-12 font-bold neon-violet rounded-full">
            Continue Learning
          </Button>
        </div>
      </Card>
    );
  }

  return null;
}